name: PayDay
version: 2.0.0
main: payday
softdepend: [Vault, Essentials]
author: Hubarz dutchy1001 and rlf
commands:
   payday:
      permission: payday.admincommand
   paycheck:
      description: Check time left
   paydebug:
      permission: payday.debug
